### ISSUE TITLE
Contributing.md Missing

### ISSUE THREAD

**Issue by dennythecoder** [dockeron/dockeron#2]
Howdy,

Not able to find the contribution file.  If it's under a different name, the link on your readme is pointing to the wrong thing.

Looks like an interesting project.

-Denny

**Comment by fluency03** [comment]
@dennythecoder I have added the CONTRIBUTING.md based on Atom's one.  Together with it, I also added Code of Conduct, Issue Template, PR Template, etc. 

Thanks :)
