### ISSUE TITLE
when npm run build

### ISSUE THREAD

**Issue by longboquan** [dockeron/dockeron#3]
### Description

electron-builder 19.45.4
Error: Unresolved node modules: vue
 at D:\frontend\dockeron\node_modules\_electron-builder@19.45.4@electron-builder\src\util\packageDependencies.ts:112:19

### Steps to Reproduce

1. npm run build

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

[node, npm, vue.js, etc.]
node 8.7.0
npm 5.4.2
vue.js 3.5.3
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by fluency03** [comment]
I cannot reproduce this issue.  I have tried clone a new project and do `npm install` and `npm run build`.  It is working fine.  

Could you provide the full logs on your console when you run install and build?

BTW, your vue.js version is 3.5.3? it does not exist.....

**Comment by longboquan** [comment]
Okay, thank you!
 
 
------------------ Original ------------------
From: "Chang Liu"; 
Date: 2017年11月16日(星期四) 晚上6:12
To: "dockeron/dockeron"; 
Cc: "东方辰"; "Author"; 
Subject: Re: [dockeron/dockeron] when npm run build (#3)

 

I cannot reproduce this issue.  I have tried clone a new project and do npm install and npm run build.  It is working fine.
 
Could you provide the full logs on your console when you run install and build?
 
BTW, your vue.js version is 3.5.3? it does not exist.....
